spring.application.name=board-service

jwt.secret=jira-super-secure-secret-key-should-be-at-least-32-characters-long

server.port=8086
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Jira
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=OFF

# RabbitMQ (future)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.template.mandatory=true

# Hikari Connection Pool (VERY IMPORTANT)
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000

# Tomcat Thread Configuration
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20

# Feign Timeouts
feign.client.config.default.connectTimeout=3000
feign.client.config.default.readTimeout=5000